### ISSUE TITLE
How to use re-captcha from inside another polymer component?

### ISSUE THREAD

**Issue by sureshvv** [cbalit/re-captcha#6]
I would like to use re-captcha from another component. I added the call to addListener inside the ready function. It loads the widget properly but clicking on it just keeps it spinning. Any help on what I am doing wrong?

**Comment by sureshvv** [comment]
I would like to use re-captcha from another component. I added the call to addListener inside the ready function. It loads the widget properly but clicking on it just keeps it spinning. Any help on what I am doing wrong?

**Comment by cbalit** [comment]
@sureshvv now I'm in holiday far away from the network. I'll keep you informed next week.

**Comment by cbalit** [comment]
@sureshvv do you have an example of failure. Because if you look at the demo of the re-captcha inside a form you can see that the re-captcha element is inside a iron-form, inside a paper-card. So it should work.

**Comment by sureshvv** [comment]
This is my repo git@github.com:sureshvv/re-captcha-test.git

You can bower install and do polymer serve --open

If you click on Make Appointment view, you will see the re-captcha rendering correctly

However if you click on it, it just spins

I think something is not wired correctly.

See src/my-view2.html to see how I have wired it into the ready function.

Thanks for any feedback. Really appreciated.

**Comment by cbalit** [comment]
@sureshvv ok it seems that the recaptha API doesn't work if the widget is in the shadow dom of a component. I guess the API need to access the widget DOM and it can't if it is in the shadow. The demo page works because all the elements are in the light DOM so that they can be manipulate by the API. Unfortunately i don't know how to deal with it for now. I will update the documentation. The only (ugly) solution for now is to pass the recaptcha form the index to the my-view using content tag. something like

in the index.html
`<my-app><re-captcha id="recaptcha1" sitekey="xxx"></re-captcha></my-app>`

In the my-app.html
`<my-view2 name="view2"><content select="re-captcha"></content></my-view2>`

In my-view2.html:
`<form is="iron-form" id="form" method="post" action="/form/handler">
          <paper-input name="name" label="name"></paper-input>
          <input name="address">
          <content select="re-captcha"></content>
      </form>`

I'll keep you inform if i found something else

Cyril

**Comment by sureshvv** [comment]
Thanks Cyril. That works for me!

The shadow dom is still in the shadow of my brain :)

**Comment by sureshvv** [comment]
http://blog.apriol.com/2016/01/components-which-refuse-to-live-in.html
